spring.application.name=ProjectHON
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/projecthon
spring.datasource.username=hon
spring.datasource.password=xansa

#Auto Generation
spring.jpa.hibernate.ddl-auto=update


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


